// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package artifacts

// ContainerArtifact defines a container image artifact.
// This artifact type represents a container image that can be pushed to registries.
// Discriminated by type!: "container".
type ContainerArtifact struct {
	Type string `json:"type"`

	Ref string `json:"ref"`

	Producer ArtifactProducer `json:"producer"`

	Publishers []string `json:"publishers"`
}

// BinaryArtifact defines a binary executable artifact.
// This artifact type represents a standalone binary executable.
// Discriminated by type!: "binary".
type BinaryArtifact struct {
	Type string `json:"type"`

	Name string `json:"name"`

	Producer ArtifactProducer `json:"producer"`

	Publishers []string `json:"publishers"`
}

// ArchiveArtifact defines an archive artifact.
// This artifact type represents a compressed archive file.
// Discriminated by type!: "archive".
type ArchiveArtifact struct {
	Type string `json:"type"`

	Compression string `json:"compression"`

	Producer ArtifactProducer `json:"producer"`

	Publishers []string `json:"publishers"`
}

// ArtifactSpec is a discriminated union of all artifact types.
// MVP: container, binary, archive
// Future: can extend with | #HelmChartArtifact | #TerraformModuleArtifact, etc.
type ArtifactSpec map[string]any

// EarthlyProducer defines an Earthly-based artifact producer.
// This producer uses Earthly targets to build artifacts.
// Discriminated by type!: "earthly".
type EarthlyProducer struct {
	Type string `json:"type"`

	Target string `json:"target"`

	Artifact string `json:"artifact,omitempty"`
}

// ArtifactProducer is a discriminated union of all producer types.
// MVP: earthly only
// Future: can extend with | #DockerProducer | #CustomProducer, etc.
type ArtifactProducer EarthlyProducer
