// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package publishers

import (
	"github.com/input-output-hk/catalyst-forge-libs/schema/common"
)

// DockerPublisher defines a Docker registry publisher configuration.
// This publisher pushes container images to a Docker registry.
// Discriminated by type!: "docker".
type DockerPublisher struct {
	// Required literal tag for discriminated union
	Type string `json:"type"`

	// Docker registry URL (e.g., "docker.io", "ghcr.io")
	Registry string `json:"registry"`

	// Registry namespace (e.g., "myorg", "username")
	Namespace string `json:"namespace"`

	// Optional credentials for registry authentication
	Credentials *common.SecretRef `json:"credentials,omitempty"`
}

// GitHubPublisher defines a GitHub Releases publisher configuration.
// This publisher publishes artifacts to GitHub Releases.
// Discriminated by type!: "github".
type GitHubPublisher struct {
	// Required literal tag for discriminated union
	Type string `json:"type"`

	// GitHub repository (e.g., "owner/repo")
	Repository string `json:"repository"`

	// Optional credentials for GitHub authentication
	Credentials *common.SecretRef `json:"credentials,omitempty"`
}

// PublisherConfig is a discriminated union of all publisher types.
// Each publisher is distinguished by its type! field.
// MVP supports: docker, github, s3.
type PublisherConfig map[string]any

// S3Publisher defines an AWS S3 bucket publisher configuration.
// This publisher uploads artifacts to an S3 bucket.
// Discriminated by type!: "s3".
type S3Publisher struct {
	// Required literal tag for discriminated union
	Type string `json:"type"`

	// S3 bucket name
	Bucket string `json:"bucket"`

	// AWS region (optional, uses default if not specified)
	Region string `json:"region,omitempty"`

	// Optional credentials for S3 authentication
	Credentials *common.SecretRef `json:"credentials,omitempty"`
}
