// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package publishers

import (
	"github.com/input-output-hk/catalyst-forge-libs/schema/common"
)

// DockerPublisher defines a Docker registry publisher configuration.
// This publisher pushes container images to a Docker registry.
// Discriminated by type!: "docker".
type DockerPublisher struct {
	Type string `json:"type"`

	Registry string `json:"registry"`

	Namespace string `json:"namespace"`

	Credentials *common.SecretRef `json:"credentials,omitempty"`
}

// GitHubPublisher defines a GitHub Releases publisher configuration.
// This publisher publishes artifacts to GitHub Releases.
// Discriminated by type!: "github".
type GitHubPublisher struct {
	Type string `json:"type"`

	Repository string `json:"repository"`

	Credentials *common.SecretRef `json:"credentials,omitempty"`
}

// PublisherConfig is a discriminated union of all publisher types.
// Each publisher is distinguished by its type! field.
// MVP supports: docker, github, s3.
type PublisherConfig map[string]any

// S3Publisher defines an AWS S3 bucket publisher configuration.
// This publisher uploads artifacts to an S3 bucket.
// Discriminated by type!: "s3".
type S3Publisher struct {
	Type string `json:"type"`

	Bucket string `json:"bucket"`

	Region string `json:"region,omitempty"`

	Credentials *common.SecretRef `json:"credentials,omitempty"`
}
