// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package phases

// PhaseDefinition defines a pipeline phase with its execution group and metadata.
// Phases with the same group number execute in parallel.
// Groups are executed sequentially in ascending order.
type PhaseDefinition struct {
	Group int64 `json:"group"`

	Description string `json:"description,omitempty"`

	Timeout string `json:"timeout,omitempty"`

	Required bool `json:"required,omitempty"`
}
