// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package common

// AWSSecretRef references a secret stored in AWS Secrets Manager.
// Discriminated by provider!: "aws".
type AWSSecretRef struct {
	Provider string `json:"provider"`

	// ARN or name of secret in AWS Secrets Manager
	Name string `json:"name"`

	// Optional key within secret
	Key string `json:"key,omitempty"`

	// AWS region (optional, uses default if not specified)
	Region string `json:"region,omitempty"`
}

// VaultSecretRef references a secret stored in HashiCorp Vault.
// Discriminated by provider!: "vault".
type VaultSecretRef struct {
	Provider string `json:"provider"`

	// Path to secret in Vault (e.g., "secret/data/myapp/api-key")
	Path string `json:"path"`

	// Optional key within secret (for KV v2)
	Key string `json:"key,omitempty"`
}

// SecretRef is a universal secret reference that can point to secrets
// in different providers (AWS Secrets Manager, HashiCorp Vault).
// This is a discriminated union based on the provider field.
type SecretRef map[string]any
