// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package common

// AWSSecretRef references a secret stored in AWS Secrets Manager.
// Discriminated by provider!: "aws".
type AWSSecretRef struct {
	Provider string `json:"provider"`

	Name string `json:"name"`

	Key string `json:"key,omitempty"`

	Region string `json:"region,omitempty"`
}

// VaultSecretRef references a secret stored in HashiCorp Vault.
// Discriminated by provider!: "vault".
type VaultSecretRef struct {
	Provider string `json:"provider"`

	Path string `json:"path"`

	Key string `json:"key,omitempty"`
}

// SecretRef is a universal secret reference that can point to secrets
// in different providers (AWS Secrets Manager, HashiCorp Vault).
// This is a discriminated union based on the provider field.
type SecretRef map[string]any
